version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Deploying to S3..."
      - ls -lrta
      - aws s3 rm s3://shop.thenextgen.solutions --recursive
      - aws s3 sync dist/nextgensolutions/browser/ s3://shop.thenextgen.solutions
