version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build
      - ls -lrta
      - cp buildspec-deploy.yml dist/nextgensolutions/browser/

artifacts:
  files:
    - '**/*'
  base-directory: dist/nextgensolutions/browser
